// Generated by scripts/build-client.mjs from src/client.js — do not edit by hand.
window.__ModuleLoader__.load({
  id: "dsh-timeline-diff",
  factory: (require) => {
    var module = { exports: {} };
    var exports = module.exports;
// Chat Timeline File Diff Viewer — client module source.
//
// This is the `dsh.client` half of the package: a plain CommonJS module whose
// exports the client module runtime mounts as a Cordis plugin. The build step
// (`scripts/build-client.mjs`) wraps this file in
// `window.__ModuleLoader__.load({ id, factory })` to produce `lib/client.js`.
//
// On-disk content is read through the harness's own `remote.workspaceFiles`
// Remote namespace (session-scoped, sandbox-bounded). This package ships no
// custom host RPC.
//
// Data model note: the persisted session log carries, per write/edit call, only
// contextual hunks (changed region +/- 3 context lines) — never the full "before"
// content of a file that already existed. Cumulative per-file diffs are therefore
// reconstructed: the current on-disk content is walked BACKWARD by undoing every
// recorded hunk (each step must match exactly once), which yields the content at
// any earlier point of the conversation; created files are walked FORWARD from
// their first full content. Any failed step makes that file fall back to the
// plain per-change rendering — never wrong data.

const React = require('react')

/** Decode a base64 byte payload from the workspaceFiles Remote into UTF-8 text. */
const b64ToText = (data) => {
  const binary = atob(data)
  const bytes = new Uint8Array(binary.length)
  for (let i = 0; i < binary.length; i += 1) bytes[i] = binary.charCodeAt(i)
  return new TextDecoder('utf-8').decode(bytes)
}

/**
 * Read one complete file's current content through the session-scoped
 * workspaceFiles Remote. Returns null when the file is absent, unreadable,
 * outside the session workspace, binary (NUL), or otherwise unavailable, so the
 * caller falls back to per-change rendering.
 */
const readWorkspaceFile = async (remote, sessionId, path) => {
  if (remote === undefined || remote === null) return null
  try {
    const result = await remote.readAll(sessionId, path)
    if (result === null || typeof result !== 'object' || result.ok !== true) return null
    const value = result.value
    if (value === null || typeof value !== 'object' || typeof value.data !== 'string') return null
    const text = b64ToText(value.data)
    return text.indexOf('\u0000') === -1 ? text : null
  } catch (error) {
    return null
  }
}

const CSS = `
.fd-view { height: 100%; display: flex; flex-direction: column; min-height: 0; }
/* The session body owns the scrollport ([data-conversation-scroll]): the view area
   grows with content, so this container must NOT clip — an overflow:auto here would
   make it the nearest scroll container and pin the sticky headers against a scroller
   that never moves. The runtime binds the sticky measurement to the real scroller. */
.fd-scroll { flex: 1 1 auto; min-height: 0; overflow: visible; padding: 16px 20px; display: flex; flex-direction: column; gap: 6px; }
.fd-summary { color: var(--dsw-alias-label-secondary); font-size: 12px; margin: 2px 4px 6px; }
.fd-empty { color: var(--dsw-alias-label-secondary); font-size: 13px; padding: 24px 4px; }
.fd-older { align-self: flex-start; margin: 2px 4px 6px; padding: 4px 10px; border: 1px solid var(--dsw-alias-border-l1); border-radius: 6px; background: var(--dsw-alias-bg-layer-1); color: var(--dsw-alias-label-primary); font: inherit; font-size: 12px; cursor: pointer; }
.fd-older:disabled { opacity: 0.6; cursor: default; }
.fd-toggle { align-self: flex-start; display: inline-flex; gap: 2px; margin: 2px 4px 6px; padding: 2px; border: 1px solid var(--dsw-alias-border-l1); border-radius: 6px; background: var(--dsw-alias-bg-layer-1); }
.fd-toggle button { border: none; background: none; color: var(--dsw-alias-label-secondary); font: inherit; font-size: 12px; padding: 3px 10px; border-radius: 4px; cursor: pointer; }
.fd-toggle button.fd-toggle-active { background: var(--dsw-alias-bg-layer-2); color: var(--dsw-alias-label-primary); }
.fd-section { display: flex; flex-direction: column; gap: 6px; }
/* The message header is a container, not a single button: it holds the section's
   collapse toggle, an Answer toggle for the turn's answer, and the answer itself —
   inside the same sticky box, so the answer stays on screen while its own diffs
   scroll under it. Nested buttons are invalid HTML, so the row is split into a real
   button (prompt) plus a sibling chip; the row's own click handler keeps the whole
   row collapsing the section the way it always did, and the chip stops propagation. */
.fd-section-user { position: sticky; top: 0; z-index: 3; display: flex; flex-direction: column; align-items: stretch; gap: 4px; width: 100%; padding: 8px 10px; border: 1px solid color-mix(in srgb, var(--dsw-alias-brand-primary) 45%, transparent); border-radius: 8px; background: color-mix(in srgb, var(--dsw-alias-brand-primary) 10%, var(--dsw-alias-bg-layer-1)); color: var(--dsw-alias-label-primary); font: inherit; font-size: 13px; text-align: left; }
.fd-section-user:hover { border-color: var(--dsw-alias-brand-primary); }
.fd-section-user-row { display: flex; align-items: center; gap: 8px; cursor: pointer; }
.fd-section-user-toggle { flex: 1 1 auto; display: flex; align-items: center; gap: 8px; min-width: 0; padding: 0; border: 0; background: none; color: inherit; font: inherit; font-size: 13px; text-align: left; cursor: pointer; }
.fd-section-user-chevron { flex: none; width: 1em; color: var(--dsw-alias-label-secondary); transition: transform 0.15s ease; }
.fd-section-user.fd-section-open .fd-section-user-chevron { transform: rotate(90deg); }
.fd-section-user-text { flex: 1 1 auto; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; font-weight: 500; }
.fd-section-user-count { flex: none; color: var(--dsw-alias-label-secondary); font-size: 12px; }
.fd-section-user-files { overflow: hidden; text-overflow: ellipsis; white-space: nowrap; font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; font-size: 11px; color: var(--dsw-alias-label-secondary); }
.fd-section-user.fd-section-closed { background: color-mix(in srgb, var(--dsw-alias-brand-primary) 6%, var(--dsw-alias-bg-layer-2)); }
.fd-section-user.fd-section-closed .fd-section-user-text { color: var(--dsw-alias-label-secondary); font-weight: 400; }
/* Leading section whose opening user message sits outside the loaded history
   window: keep the exact header chrome so its file rows match the following
   sections, but mute the placeholder label so it is not mistaken for a prompt. */
.fd-section-user.fd-section-earlier .fd-section-user-text { color: var(--dsw-alias-label-secondary); font-weight: 400; }
/* Answer chip, and the card it opens. The answer is a floating card, not a row in
   the header: position:absolute keeps it out of the header's flow, so the pinned
   header never grows and no sticky offset has to be re-measured, and the diffs keep
   their full height underneath while the answer hovers over them. It occupies the
   right half of the message column — the prompt keeps the left — and is
   height-capped with its own scroll so a long answer cannot swallow the viewport
   either. */
.fd-section-user-answer-toggle { flex: none; padding: 1px 8px; border: 1px solid var(--dsw-alias-border-l1); border-radius: 999px; background: var(--dsw-alias-bg-layer-1); color: var(--dsw-alias-label-secondary); font: inherit; font-size: 11px; line-height: 16px; cursor: pointer; }
.fd-section-user-answer-toggle:hover { border-color: var(--dsw-alias-brand-primary); color: var(--dsw-alias-label-primary); }
.fd-section-user-answer-toggle[aria-expanded="true"] { border-color: var(--dsw-alias-brand-primary); color: var(--dsw-alias-label-primary); }
/* The open section lifts above its later siblings, whose headers share z-index 3 and
   would otherwise paint over the floating card the moment they pin. */
.fd-section-user.fd-section-answer-open { z-index: 5; }
.fd-section-answer { position: absolute; top: calc(100% + 6px); left: 50%; right: 0; z-index: 1; max-height: min(60vh, 560px); overflow-y: auto; overscroll-behavior: contain; padding: 10px 12px; border: 1px solid var(--dsw-alias-border-l1); border-radius: 10px; background: var(--dsw-alias-bg-layer-1); box-shadow: var(--dsw-elevation-panel); color: var(--dsw-alias-label-primary); font-size: 13px; line-height: 1.6; text-align: left; overflow-wrap: anywhere; }
.fd-section-answer-meta { display: flex; align-items: center; gap: 8px; margin-bottom: 6px; padding-bottom: 6px; border-bottom: 1px solid var(--dsw-alias-border-l1); color: var(--dsw-alias-label-caption); font-size: 11px; }
.fd-section-answer-load { flex: none; margin-left: auto; padding: 1px 8px; border: 1px solid var(--dsw-alias-border-l1); border-radius: 999px; background: var(--dsw-alias-bg-layer-2); color: var(--dsw-alias-label-primary); font: inherit; font-size: 11px; line-height: 16px; cursor: pointer; }
.fd-section-answer-load:hover:not(:disabled) { border-color: var(--dsw-alias-brand-primary); }
.fd-section-answer-load:disabled { opacity: 0.6; cursor: default; }
.fd-section-answer-text { overflow-wrap: anywhere; }
.fd-change { position: sticky; top: var(--fd-sticky-offset, 0px); z-index: 2; display: flex; align-items: baseline; gap: 8px; width: 100%; padding: 6px 8px; border: none; border-radius: 6px; background: none; color: var(--dsw-alias-label-primary); font: inherit; text-align: left; cursor: pointer; }
.fd-change:hover { background: var(--dsw-alias-bg-layer-2); }
.fd-change-index { flex: none; min-width: 3ch; color: var(--dsw-alias-label-secondary); font-size: 12px; text-align: right; }
.fd-change-path { font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; font-size: 13px; }
/* One cumulative (aggregated) diff per file — timeline "total in this message" rows.
   The row header is sticky inside its own .fd-total-body containing block, so
   while scrolling a long diff the file name stays visible, and consecutive
   file rows pin one at a time without overlapping. */
.fd-total { position: sticky; top: var(--fd-sticky-offset, 0px); z-index: 2; display: flex; align-items: baseline; gap: 8px; width: 100%; padding: 6px 8px; border: none; border-radius: 6px; background: color-mix(in srgb, var(--dsw-alias-brand-primary) 7%, transparent); color: var(--dsw-alias-label-primary); font: inherit; text-align: left; cursor: pointer; }
.fd-total:hover { background: color-mix(in srgb, var(--dsw-alias-brand-primary) 13%, transparent); }
/* A pinned filename header must be opaque, or the diff scrolling underneath
   shows through it. Both header kinds (.fd-change fallback entries and File-mode
   groups, .fd-total aggregates) paint the same tint-aware surface while stuck so
   the pinned row looks identical whichever kind it is; the untinted layer it
   used before made one header go near-black while the other kept a bare tint. */
.fd-change.fd-stuck,
.fd-total.fd-stuck { background: color-mix(in srgb, var(--dsw-alias-brand-primary) 7%, var(--dsw-alias-bg-layer-1)); box-shadow: 0 1px 0 0 var(--dsw-alias-border-l1); }
.fd-total-mark { flex: none; min-width: 3ch; color: var(--dsw-alias-brand-primary); font-size: 12px; text-align: right; font-weight: 600; }
.fd-total-path { font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; font-size: 13px; }
.fd-total-meta { flex: 1 1 auto; text-align: right; color: var(--dsw-alias-label-secondary); font-size: 12px; }
.fd-total-body { display: flex; flex-direction: column; gap: 6px; padding: 2px 10px 8px; }
.fd-reason { color: var(--dsw-alias-label-secondary); font-size: 11px; padding: 0 10px 4px; }
.fd-netzero { color: var(--dsw-alias-label-secondary); font-size: 12px; padding: 4px 10px 6px; }
.fd-inset { display: flex; flex-direction: column; gap: 6px; padding: 2px 0 4px; }
.fd-inset .fd-older { margin: 0 8px; }
.fd-hunk { border: 1px solid var(--dsw-alias-border-l1); border-radius: 8px; background: var(--dsw-alias-bg-layer-1); overflow: hidden; }
.fd-line { display: flex; gap: 10px; padding: 0 10px; font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; font-size: 12px; line-height: 1.7; }
.fd-sign { flex: none; width: 1ch; color: var(--dsw-alias-label-secondary); user-select: none; }
.fd-text { white-space: pre; overflow-wrap: anywhere; }
.fd-line-add { background: color-mix(in srgb, var(--dsw-alias-state-success-primary) 12%, transparent); }
.fd-line-del { background: color-mix(in srgb, var(--dsw-alias-state-error-primary) 12%, transparent); }
.fd-line-add .fd-sign { color: var(--dsw-alias-state-success-primary); }
.fd-line-del .fd-sign { color: var(--dsw-alias-state-error-primary); }
/* Tab placement is owned by the slot registry: the harness sorts conversation.view
   entries by their order field (chat 0, trajectory 10, diff 20), so the Diff tab
   already renders rightmost. Do NOT reorder the tablist with positional CSS here —
   that assumes a fixed DOM order and flips the tabs whenever the harness changes it. */
/* Turn navigator rail — the Chat tab's helper, reimplemented for this view. One
   fixed-pitch mark per Turn of the session on the right edge: loaded marks scroll
   this view to the Turn's message section, marks for Turns outside the loaded
   window page history in first, and hover/focus opens a note card for that Turn
   with its prompt, its full final answer, and the files it changed. Geometry reads
   the conversation variables the shipped rail reads (viewport height, composer
   height), so both rails sit at the same place; .fd-scroll's 20px side padding is
   folded into the right offset. No container query units here — adding
   container-type to an ancestor of the sticky section headers risks their pinning
   behaviour. */
.fd-rail-slot { position: sticky; top: 0; z-index: 6; height: 0; pointer-events: none; }
.fd-rail-frame { --fd-rail-band: calc(var(--dsh-conversation-viewport-height, 100dvh) - var(--dsh-composer-height, 152px)); --fd-rail-preview-height: min(360px, calc(var(--fd-rail-band) - 96px)); position: absolute; top: calc(var(--fd-rail-band) / 2); right: -8px; width: 28px; height: min(var(--fd-rail-natural-height), max(0px, calc(var(--fd-rail-band) - 64px)), 420px); cursor: pointer; pointer-events: auto; transition: height 0.22s cubic-bezier(0.2, 0.8, 0.2, 1); transform: translateY(-50%); }
.fd-rail-scroller { position: absolute; inset: 0; overflow-y: auto; overscroll-behavior: contain; scrollbar-width: none; }
.fd-rail-scroller::-webkit-scrollbar { display: none; }
.fd-rail-fade-top { mask-image: linear-gradient(#0000 0, #000 24px 100%); }
.fd-rail-fade-bottom { mask-image: linear-gradient(#000 0 calc(100% - 24px), #0000 100%); }
.fd-rail-fade-top.fd-rail-fade-bottom { mask-image: linear-gradient(#0000 0, #000 24px calc(100% - 24px), #0000 100%); }
.fd-rail-marks { position: relative; height: var(--fd-rail-natural-height); }
.fd-rail-mark-position { position: absolute; left: 0; right: 0; height: 10px; top: calc(var(--fd-rail-natural-position) + var(--fd-rail-inset)); transform: translateY(-50%); transition: top 0.22s cubic-bezier(0.2, 0.8, 0.2, 1); animation: 0.15s ease-out fd-rail-mark-enter; }
.fd-rail-mark { position: absolute; inset: 0 0 0 auto; width: 20px; padding: 0; border: 0; border-radius: 8px; background: none; cursor: pointer; }
.fd-rail-mark::before { content: ""; position: absolute; top: 50%; right: 0; width: 12px; height: 2px; border-radius: 2px; background: var(--dsw-alias-border-l4); transform: translateY(-50%); transition: width 0.14s, background-color 0.14s; }
/* A Turn the loaded window does not hold yet: the mark is short and quiet until
   its jump pages it in. A loaded Turn with no file change keeps a dimmed mark so
   the rail still maps the whole conversation without pretending it has diffs. */
.fd-rail-mark-unloaded::before { width: 8px; opacity: 0.6; }
.fd-rail-mark-nodiff::before { opacity: 0.45; }
.fd-rail-mark-preview::before { width: 18px; background: var(--dsw-alias-label-tertiary); opacity: 1; }
.fd-rail-mark-active::before { width: 20px; background: var(--dsw-alias-label-primary); opacity: 1; }
.fd-rail-mark-busy::before { animation: 1s ease-in-out infinite fd-rail-mark-busy; }
.fd-rail-mark:focus-visible { outline: 1px solid var(--dsw-alias-state-business-primary); outline-offset: 2px; }
.fd-rail-mark:focus-visible::before { width: 20px; background: var(--dsw-alias-state-business-primary); opacity: 1; }
/* The hover/focus note. Unlike the shipped rail (a fixed 100px preview) this card
   is the Turn's reading surface: it is flush with the frame's left edge and takes
   pointer events, so the pointer can travel from a mark onto the note without a
   dead gap, and a long answer scrolls inside the card instead of being clipped.
   The card is tall enough to hold a full answer, bounded by the space above the
   composer (--fd-rail-preview-height). */
.fd-rail-preview { position: absolute; right: 100%; box-sizing: border-box; width: min(420px, calc(100vw - 120px)); max-height: var(--fd-rail-preview-height); display: flex; flex-direction: column; padding: 10px 12px; border: 0; border-radius: 10px; background: var(--dsw-alias-bg-layer-1); box-shadow: var(--dsw-elevation-panel); color: var(--dsw-alias-label-primary); cursor: default; overflow: hidden; top: clamp(0px, calc(var(--fd-rail-natural-position) + var(--fd-rail-inset) - var(--fd-rail-scroll-top, 0px) - var(--fd-rail-preview-height) / 2), calc(100% - var(--fd-rail-preview-height))); transition: top 0.14s cubic-bezier(0.2, 0.8, 0.2, 1); animation: 0.12s ease-out fd-rail-preview-enter; }
.fd-rail-preview-prompt { flex: none; display: -webkit-box; -webkit-box-orient: vertical; -webkit-line-clamp: 2; overflow: hidden; font: var(--dsw-font-xs-strong-13); }
/* The full answer, not a line-clamped teaser: whitespace is preserved and the
   block scrolls on its own when the answer is taller than the card. */
.fd-rail-preview-answer { flex: 1 1 auto; min-height: 0; margin-top: 6px; padding-top: 6px; border-top: 1px solid var(--dsw-alias-border-l1); color: var(--dsw-alias-label-secondary); font: var(--dsw-font-xxs-12); overflow-wrap: anywhere; overflow-y: auto; overscroll-behavior: contain; scrollbar-width: thin; }
.fd-rail-preview-answer-muted { color: var(--dsw-alias-label-caption); font-style: italic; }
.fd-rail-preview-detail { flex: none; margin-top: 6px; padding-top: 6px; border-top: 1px solid var(--dsw-alias-border-l1); color: var(--dsw-alias-brand-primary); font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; font-size: 11px; overflow-wrap: anywhere; }
@keyframes fd-rail-mark-enter { 0% { opacity: 0 } to { opacity: 1 } }
@keyframes fd-rail-preview-enter { 0% { opacity: 0; transform: translate(4px) } to { opacity: 1; transform: translate(0) } }
@keyframes fd-rail-mark-busy { 0%, to { opacity: 1 } 50% { opacity: 0.35 } }
@media (max-width: 900px) { .fd-rail-slot { display: none; } }
@media (prefers-reduced-motion: reduce) { .fd-rail-frame, .fd-rail-mark-position, .fd-rail-mark::before, .fd-rail-mark-busy::before, .fd-rail-preview { transition: none; animation: none; } }
/* Answer text, in both surfaces. Rendered Markdown carries almost no class names
   (the harness styles its own chat containers), so the block elements get the
   spacing and code surface this view uses; the plain fallback preserves the
   message's own line breaks. */
.fd-answer-plain { white-space: pre-wrap; overflow-wrap: anywhere; }
.fd-answer-markdown > :first-child { margin-top: 0; }
.fd-answer-markdown > :last-child { margin-bottom: 0; }
.fd-answer-markdown p { margin: 0 0 8px; }
.fd-answer-markdown ul, .fd-answer-markdown ol { margin: 0 0 8px; padding-left: 20px; }
.fd-answer-markdown li { margin: 0 0 2px; }
.fd-answer-markdown h1, .fd-answer-markdown h2, .fd-answer-markdown h3, .fd-answer-markdown h4 { margin: 10px 0 6px; font-size: 13px; font-weight: 600; }
.fd-answer-markdown code { padding: 1px 4px; border-radius: 4px; background: var(--dsw-alias-bg-layer-2); font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; font-size: 12px; }
.fd-answer-markdown pre { margin: 0 0 8px; padding: 8px 10px; border: 1px solid var(--dsw-alias-border-l1); border-radius: 6px; background: var(--dsw-alias-bg-base); overflow-x: auto; }
.fd-answer-markdown pre code { padding: 0; background: none; }
.fd-answer-markdown a { color: var(--dsw-alias-brand-primary); }
.fd-answer-markdown blockquote { margin: 0 0 8px; padding-left: 10px; border-left: 2px solid var(--dsw-alias-border-l1); color: var(--dsw-alias-label-secondary); }
.fd-answer-markdown table { margin: 0 0 8px; border-collapse: collapse; }
.fd-answer-markdown th, .fd-answer-markdown td { padding: 3px 8px; border: 1px solid var(--dsw-alias-border-l1); }
`

let viewMode = 'session'

const plugin = {
  name: 'timeline-diff',
  inject: ['slots', 'sessions', 'remote.workspaceFiles'],
  apply(ctx) {
    const slots = ctx.get('slots')
    if (slots === undefined) return

    const remoteFiles = ctx.get('remote.workspaceFiles')

    // The harness's own Markdown renderer, reached through the shell's static
    // module table (`staticModules`: react, react/jsx-runtime, react-dom,
    // react-dom/client, cordis, dsh-client-store, dsh-client-ui-slots,
    // dsh-client-ui-primitives, dsh-client-ui-dockkit). Entries there resolve
    // exactly like the `react` require above — no dependency, no
    // `dsh.client.external` graph edge, and the same GFM+KaTeX rendering the Chat
    // tab gives assistant text. Guarded because a harness that drops the entry, or
    // the dynamic payload where `require` does not exist at all, must degrade to
    // pre-wrapped plain text rather than take the whole view down.
    const MarkdownText = (() => {
      try {
        const primitives = require('@deepseek-ai/dsh-client-ui-primitives')
        if (primitives === null || primitives === undefined) return null
        return primitives.MarkdownText === undefined || primitives.MarkdownText === null ? null : primitives.MarkdownText
      } catch (error) {
        return null
      }
    })()

    /**
     * An assistant answer: Markdown when the harness renderer is reachable, the
     * message's own text (line breaks preserved) otherwise. `className` carries the
     * surface's own layout; the wrapper adds the block-element styling.
     */
    const AnswerText = ({ text, className }) => MarkdownText === null
      ? React.createElement('div', { className: `${className} fd-answer-plain` }, text)
      : React.createElement('div', { className: `${className} fd-answer-markdown` },
        React.createElement(MarkdownText, { text }))

    // ------------------------------------------------------------------ //
    // Pure core (kept contiguous for offline unit tests between markers) //
    // ------------------------------------------------------------------ //
    // __fd-core-begin

    const isFileDiff = (d) => d !== null && typeof d === 'object' && typeof d.path === 'string' && typeof d.newText === 'string'

    const relativize = (path, cwd) => {
      if (cwd === undefined || cwd === '') return path
      const root = cwd.replace(/[/\\]+$/, '')
      if (path.startsWith(`${root}/`) || path.startsWith(`${root}\\`)) return path.slice(root.length + 1)
      return path
    }

    // Whole-file diff recovered from a persisted `write` call head. The platform
    // itself renders a create card from the call arguments when the result meta
    // carries no hunks, so this mirrors that fallback for the log's own shape.
    const diffFromWriteCall = (argsRaw) => {
      if (typeof argsRaw !== 'string' || argsRaw === '') return null
      let args = null
      try { args = JSON.parse(argsRaw) } catch (error) { return null }
      if (args === null || typeof args !== 'object') return null
      const path = args.file_path !== undefined ? args.file_path : (args.filePath !== undefined ? args.filePath : args.path)
      const content = args.content
      if (typeof path !== 'string' || typeof content !== 'string') return null
      return { path, oldText: null, newText: content }
    }

    const extractHunks = (node) => {
      if (node.kind !== 'tool-result' || node.isError) return null
      const meta = node.meta
      let hasMetaDiffs = false
      if (meta !== null && typeof meta === 'object' && Array.isArray(meta.diffs)) {
        hasMetaDiffs = true
        const diffs = meta.diffs.filter(isFileDiff)
        if (diffs.length > 0) return diffs
      }
      // Older harness layouts exposed per-change cards as persisted views.
      const result = node.resultView
      if (result !== null && result !== undefined && result.card === 'diff' && Array.isArray(result.diffs)) {
        const diffs = result.diffs.filter(isFileDiff)
        if (diffs.length > 0) return diffs
      }
      const call = node.callView
      if (call !== null && call !== undefined && call.card === 'diff' && Array.isArray(call.diffs)) {
        return call.diffs.filter(isFileDiff)
      }
      // Current harness: a create (and a no-op write) persists `meta.diffs: []`;
      // the node only carries the persisted call head, so fall back to the call
      // arguments — the whole-file content — for `write` calls.
      const callHead = node.call !== null && typeof node.call === 'object' ? node.call : null
      if (callHead !== null && callHead.name === 'write' && typeof callHead.argsRaw === 'string') {
        const fallback = diffFromWriteCall(callHead.argsRaw)
        if (fallback !== null) return [fallback]
      }
      if (hasMetaDiffs) return null
      return null
    }

    const userText = (node) => {
      let text = ''
      for (const block of node.content) {
        if (block !== null && typeof block === 'object' && block.type === 'text' && typeof block.text === 'string') {
          text += (text === '' ? '' : ' ') + block.text
        }
      }
      const trimmed = text.trim()
      return trimmed.length > 160 ? `${trimmed.slice(0, 160)}…` : trimmed
    }

    // One assistant message's visible text, in full: the answer itself, not the
    // host's three-line preview. Reasoning blocks are deliberately excluded — the
    // answer explains the change, it does not expose the model's thinking — and a
    // message with no text (a tool-only step) returns '', so a section keeps its
    // newest text-bearing answer.
    //
    // The block discriminators differ by role and this is easy to get wrong: an
    // assistant node's `blocks` are Chat `AssistantBlock`s, tagged `kind` (the Chat
    // target converts the core `type`-tagged blocks through `toAssistantBlocks`),
    // while a user node's `content` keeps the core `type`. Both are accepted so a
    // harness that stops converting does not silently empty every answer — which is
    // exactly what `type`-only matching did against the real log.
    const assistantText = (node) => {
      if (node.kind !== 'assistant' || !Array.isArray(node.blocks)) return ''
      let text = ''
      for (const block of node.blocks) {
        if (block === null || typeof block !== 'object') continue
        const isText = (block.kind === 'text' || block.type === 'text') && typeof block.text === 'string'
        if (!isText) continue
        text += (text === '' ? '' : '\n\n') + block.text
      }
      return text.trim()
    }

    const splitLines = (text) => {
      const body = text.endsWith('\n') ? text.slice(0, -1) : text
      return body === '' ? [] : body.split('\n')
    }

    // Line endings are LF-normalized by the filesystem backend, so normalize
    // hunk text and disk content to the same basis before substring matching.
    const canonText = (text) => {
      if (text === null || text === undefined) return ''
      return String(text).replace(/\r\n/g, '\n').replace(/\r/g, '\n')
    }

    // -1 missing, -2 ambiguous, >= 0 the single occurrence.
    const findIndex = (text, needle) => {
      const i = text.indexOf(needle)
      if (i === -1) return -1
      if (text.indexOf(needle, i + 1) !== -1) return -2
      return i
    }

    const replaceAt = (text, at, len, next) => text.slice(0, at) + next + text.slice(at + len)

    // Forward: apply one tool-call's hunks (same "before" state) to `state`.
    // Hunks of one call are splices against one pre-call text, so match
    // positions are resolved up front and applied tail-to-head.
    // A hunk with oldText === null is a whole-content set (create into an
    // empty/absent file) and is only valid when the state is empty.
    const applyEvent = (state, hunks) => {
      const subs = []
      let whole = null
      for (const h of hunks) {
        if (h.oldText === null || h.oldText === undefined) {
          if (state !== '') return { ok: false }
          whole = h.newText
        } else {
          const at = findIndex(state, h.oldText)
          if (at < 0) return { ok: false }
          subs.push({ at, len: h.oldText.length, next: h.newText })
        }
      }
      subs.sort((a, b) => b.at - a.at)
      let cur = state
      for (const op of subs) cur = replaceAt(cur, op.at, op.len, op.next)
      if (whole !== null) cur = whole
      return { state: cur, ok: true }
    }

    // Backward: undo one tool-call's hunks (the inverse of applyEvent).
    const undoEvent = (state, hunks) => {
      const subs = []
      let whole = null
      for (const h of hunks) {
        if (h.oldText === null || h.oldText === undefined) {
          if (state !== h.newText) return { ok: false }
          whole = ''
        } else {
          const at = findIndex(state, h.newText)
          if (at < 0) return { ok: false }
          subs.push({ at, len: h.newText.length, next: h.oldText })
        }
      }
      subs.sort((a, b) => b.at - a.at)
      let cur = state
      for (const op of subs) cur = replaceAt(cur, op.at, op.len, op.next)
      if (whole !== null) cur = whole
      return { state: cur, ok: true }
    }

    // Group a conversation snapshot's file changes.
    // sections: per user message, the chronological per-hunk entries (identical
    //   semantics/order to the original Timeline view). Each section also records
    //   the `seq` of the node that opened it, which is how a section is matched to
    //   its Turn for the navigator rail, and `answer`: the full text of the last
    //   assistant message the turn produced — what the rail's note card shows.
    // files: per path, the ordered change events; one event = one tool call's
    //   hunks for that file, tagged with the section it happened in.
    const buildModel = (nodes, cwd) => {
      if (!Array.isArray(nodes)) return { sections: [], files: [] }
      const sections = []
      const byPath = new Map()
      let current = null
      const openSection = (user, node) => {
        current = { user, changes: [], seq: typeof node.seq === 'number' ? node.seq : null, answer: '' }
        sections.push(current)
        return current
      }
      for (const node of nodes) {
        if (node.kind === 'user') {
          openSection(userText(node), node)
          continue
        }
        if (node.kind === 'assistant') {
          // A window can open on an assistant step whose prompt is outside it; the
          // placeholder section keeps that answer attached to the turn it belongs
          // to instead of dropping it.
          if (current === null) openSection(null, node)
          const text = assistantText(node)
          if (text !== '') current.answer = text
          continue
        }
        const diffs = extractHunks(node)
        if (diffs === null) continue
        if (current === null) openSection(null, node)
        const sec = sections.length - 1
        const byFile = new Map()
        for (const d of diffs) {
          const path = relativize(d.path, cwd)
          let rec = byPath.get(path)
          if (rec === undefined) {
            rec = { path, events: [] }
            byPath.set(path, rec)
          }
          let ev = byFile.get(path)
          if (ev === undefined) {
            ev = { sec, hunks: [] }
            byFile.set(path, ev)
          }
          const oldText = d.oldText === null ? null : canonText(d.oldText)
          const newText = canonText(d.newText)
          ev.hunks.push({ oldText, newText })
          current.changes.push({ path, oldText, newText })
        }
        for (const [path, ev] of byFile) byPath.get(path).events.push(ev)
      }
      return { sections, files: [...byPath.values()] }
    }

    // Reconstruct the content of a file at every event boundary.
    // states[i] = content BEFORE event i (states[0] = at conversation start,
    // states[n] = after the last event).
    //   created file  -> forward walk from the first full content.
    //   pre-existing  -> backward walk from the current disk content.
    const buildPlan = (file, disk) => {
      const events = file.events
      if (events.length === 0) return { ok: false, reason: '' }
      let size = 0
      for (const ev of events) {
        for (const h of ev.hunks) {
          size += (h.oldText === null ? 0 : h.oldText.length) + h.newText.length
        }
      }
      if (events.length > 300 || size > 8e6) {
        return { ok: false, reason: 'file too large for a cumulative diff — showing individual changes.' }
      }
      const created = events[0].hunks.length === 1 && (events[0].hunks[0].oldText === null || events[0].hunks[0].oldText === undefined)
      const states = new Array(events.length + 1)
      if (created) {
        states[0] = ''
        let cur = events[0].hunks[0].newText
        states[1] = cur
        for (let i = 1; i < events.length; i += 1) {
          const r = applyEvent(cur, events[i].hunks)
          if (!r.ok) {
            return { ok: false, reason: 'history is not fully reconstructible (a change no longer matches) — showing individual changes.' }
          }
          cur = r.state
          states[i + 1] = cur
        }
        return { ok: true, created: true, states, diverged: disk !== null && disk !== cur }
      }
      if (disk === null) {
        return { ok: false, reason: 'current file content is unavailable (deleted or unreadable) — showing individual changes.' }
      }
      let cur = disk
      states[events.length] = cur
      for (let i = events.length - 1; i >= 0; i -= 1) {
        const r = undoEvent(cur, events[i].hunks)
        if (!r.ok) {
          return { ok: false, reason: 'file content no longer matches this session\u2019s changes (edited outside it?) — showing individual changes.' }
        }
        cur = r.state
        states[i] = cur
      }
      return { ok: true, created: false, states, diverged: false }
    }

    // ---- line diff (patience + small LCS, patch-style output) ----

    const dpEmit = (ops, A, B, aLo, aHi, bLo, bHi) => {
      const na = aHi - aLo
      const nb = bHi - bLo
      const dp = new Array(na + 1)
      dp[0] = new Int32Array(nb + 1)
      for (let i = 1; i <= na; i += 1) {
        const prev = dp[i - 1]
        const row = new Int32Array(nb + 1)
        for (let j = 1; j <= nb; j += 1) {
          if (A[aLo + i - 1] === B[bLo + j - 1]) row[j] = prev[j - 1] + 1
          else row[j] = prev[j] >= row[j - 1] ? prev[j] : row[j - 1]
        }
        dp[i] = row
      }
      const tmp = []
      let i = na
      let j = nb
      while (i > 0 && j > 0) {
        if (A[aLo + i - 1] === B[bLo + j - 1]) {
          tmp.push({ k: 'eq', line: A[aLo + i - 1] })
          i -= 1
          j -= 1
        } else if (dp[i - 1][j] >= dp[i][j - 1]) {
          tmp.push({ k: 'del', line: A[aLo + i - 1] })
          i -= 1
        } else {
          tmp.push({ k: 'add', line: B[bLo + j - 1] })
          j -= 1
        }
      }
      while (i > 0) {
        tmp.push({ k: 'del', line: A[aLo + i - 1] })
        i -= 1
      }
      while (j > 0) {
        tmp.push({ k: 'add', line: B[bLo + j - 1] })
        j -= 1
      }
      for (let t = tmp.length - 1; t >= 0; t -= 1) ops.push(tmp[t])
    }

    // Emit ops for A[aLo..aHi) vs B[bLo..bHi) (both sides may differ).
    const solveRange = (ops, A, B, aLo, aHi, bLo, bHi) => {
      if (aLo >= aHi) {
        for (let i = bLo; i < bHi; i += 1) ops.push({ k: 'add', line: B[i] })
        return
      }
      if (bLo >= bHi) {
        for (let i = aLo; i < aHi; i += 1) ops.push({ k: 'del', line: A[i] })
        return
      }
      while (aLo < aHi && bLo < bHi && A[aLo] === B[bLo]) {
        ops.push({ k: 'eq', line: A[aLo] })
        aLo += 1
        bLo += 1
      }
      if (aLo >= aHi) {
        for (let i = bLo; i < bHi; i += 1) ops.push({ k: 'add', line: B[i] })
        return
      }
      if (bLo >= bHi) {
        for (let i = aLo; i < aHi; i += 1) ops.push({ k: 'del', line: A[i] })
        return
      }
      let tail = 0
      while (tail < aHi - aLo && tail < bHi - bLo && A[aHi - 1 - tail] === B[bHi - 1 - tail]) tail += 1
      const ma = aHi - tail
      const mb = bHi - tail
      const na = ma - aLo
      const nb = mb - bLo
      if (na > 0 && nb > 0 && na * nb <= 24000) {
        dpEmit(ops, A, B, aLo, ma, bLo, mb)
      } else if (na === 0) {
        for (let i = bLo; i < mb; i += 1) ops.push({ k: 'add', line: B[i] })
      } else if (nb === 0) {
        for (let i = aLo; i < ma; i += 1) ops.push({ k: 'del', line: A[i] })
      } else {
        // Patience anchors over lines unique in both sub-ranges.
        const countA = new Map()
        const countB = new Map()
        for (let i = aLo; i < ma; i += 1) countA.set(A[i], (countA.get(A[i]) || 0) + 1)
        for (let i = bLo; i < mb; i += 1) countB.set(B[i], (countB.get(B[i]) || 0) + 1)
        const pairs = []
        for (let i = aLo; i < ma; i += 1) {
          const line = A[i]
          if (countA.get(line) !== 1 || countB.get(line) !== 1) continue
          for (let j = bLo; j < mb; j += 1) {
            if (B[j] === line) {
              pairs.push({ a: i, b: j })
              break
            }
          }
        }
        if (pairs.length === 0) {
          for (let i = aLo; i < ma; i += 1) ops.push({ k: 'del', line: A[i] })
          for (let i = bLo; i < mb; i += 1) ops.push({ k: 'add', line: B[i] })
          for (let i = 0; i < tail; i += 1) ops.push({ k: 'eq', line: A[aHi - tail + i] })
          return
        }
        // Longest increasing subsequence of `b` over ascending `a`.
        const nodes = []
        const tails = []
        for (const pair of pairs) {
          let lo = 0
          let hi = tails.length
          while (lo < hi) {
            const mid = (lo + hi) >> 1
            if (nodes[tails[mid]].b >= pair.b) hi = mid
            else lo = mid + 1
          }
          const prev = lo > 0 ? tails[lo - 1] : -1
          nodes.push({ a: pair.a, b: pair.b, prev })
          tails[lo] = nodes.length - 1
        }
        const anchors = []
        let cur = tails.length > 0 ? tails[tails.length - 1] : -1
        while (cur !== -1) {
          anchors.push({ a: nodes[cur].a, b: nodes[cur].b })
          cur = nodes[cur].prev
        }
        anchors.reverse()
        if (anchors.length === 0) {
          for (let i = aLo; i < ma; i += 1) ops.push({ k: 'del', line: A[i] })
          for (let i = bLo; i < mb; i += 1) ops.push({ k: 'add', line: B[i] })
        } else {
          let pa = aLo
          let pb = bLo
          for (const anchor of anchors) {
            solveRange(ops, A, B, pa, anchor.a, pb, anchor.b)
            ops.push({ k: 'eq', line: A[anchor.a] })
            pa = anchor.a + 1
            pb = anchor.b + 1
          }
          solveRange(ops, A, B, pa, ma, pb, mb)
        }
      }
      for (let i = 0; i < tail; i += 1) ops.push({ k: 'eq', line: A[aHi - tail + i] })
    }

    const opsFor = (A, B) => {
      const ops = []
      solveRange(ops, A, B, 0, A.length, 0, B.length)
      return ops
    }

    const rowOf = (op) => {
      if (op.k === 'eq') return { kind: 'ctx', text: op.line }
      return { kind: op.k, text: op.line }
    }

    // Patch-style rows: change runs plus up to `ctxN` context lines around them.
    const buildRows = (ops, ctxN) => {
      const rows = []
      if (ops.length === 0) return rows
      const runs = []
      let i = 0
      while (i < ops.length) {
        if (ops[i].k !== 'eq') {
          let j = i
          while (j < ops.length && ops[j].k !== 'eq') j += 1
          runs.push([i, j])
          i = j
        } else i += 1
      }
      const merged = []
      for (const run of runs) {
        if (merged.length === 0) {
          merged.push([run[0], run[1]])
          continue
        }
        const last = merged[merged.length - 1]
        if (run[0] - last[1] < 2 * ctxN) last[1] = run[1]
        else merged.push([run[0], run[1]])
      }
      for (const [rs, re] of merged) {
        let p = rs - 1
        let c = 0
        while (p >= 0 && ops[p].k === 'eq' && c < ctxN) {
          p -= 1
          c += 1
        }
        for (let k = p + 1; k < rs; k += 1) rows.push(rowOf(ops[k]))
        for (let k = rs; k < re; k += 1) rows.push(rowOf(ops[k]))
        let q = re
        c = 0
        while (q < ops.length && ops[q].k === 'eq' && c < ctxN) {
          q += 1
          c += 1
        }
        for (let k = re; k < q; k += 1) rows.push(rowOf(ops[k]))
      }
      return rows
    }

    // Cumulative diff between two whole file contents (already canonical).
    const computeDiff = (before, after) => {
      const aText = before === null || before === undefined ? '' : canonText(String(before))
      const bText = after === null || after === undefined ? '' : canonText(String(after))
      const A = splitLines(aText)
      const B = splitLines(bText)
      let s = 0
      while (s < A.length && s < B.length && A[s] === B[s]) s += 1
      let eA = A.length
      let eB = B.length
      while (eA > s && eB > s && A[eA - 1] === B[eB - 1]) {
        eA -= 1
        eB -= 1
      }
      const ops = []
      solveRange(ops, A, B, s, eA, s, eB)
      let adds = 0
      let dels = 0
      for (const op of ops) {
        if (op.k === 'add') adds += 1
        else if (op.k === 'del') dels += 1
      }
      return {
        rows: buildRows(ops, 3),
        adds,
        dels,
        same: aText === bText,
      }
    }

    // __fd-core-end

    // ------------------------------------------------------------------ //
    // Timeline section with per-message cumulative ("total") rows          //
    // ------------------------------------------------------------------ //
    const Hunk = ({ hunk }) => {
      const lines = hunkLines(hunk.oldText, hunk.newText)
      const rows = lines.map((line, index) => React.createElement('div', { key: index, className: `fd-line fd-line-${line.kind}` },
        React.createElement('span', { className: 'fd-sign' }, line.kind === 'add' ? '+' : line.kind === 'del' ? '-' : ' '),
        React.createElement('span', { className: 'fd-text' }, line.text)))
      return React.createElement('div', { className: 'fd-hunk' }, ...rows)
    }

    const hunkLines = (oldText, newText) => {
      const oldLines = oldText === null ? [] : splitLines(oldText)
      const newLines = splitLines(newText)
      let start = 0
      while (start < oldLines.length && start < newLines.length && oldLines[start] === newLines[start]) start += 1
      let oldEnd = oldLines.length
      let newEnd = newLines.length
      while (oldEnd > start && newEnd > start && oldLines[oldEnd - 1] === newLines[newEnd - 1]) { oldEnd -= 1; newEnd -= 1 }
      const out = []
      for (let i = 0; i < start; i += 1) out.push({ kind: 'ctx', text: oldLines[i] })
      for (let i = start; i < oldEnd; i += 1) out.push({ kind: 'del', text: oldLines[i] })
      for (let i = start; i < newEnd; i += 1) out.push({ kind: 'add', text: newLines[i] })
      for (let i = oldEnd; i < oldLines.length; i += 1) out.push({ kind: 'ctx', text: oldLines[i] })
      return out
    }

    const RowLines = ({ rows }) => {
      const elements = rows.map((line, index) => React.createElement('div', { key: index, className: `fd-line fd-line-${line.kind}` },
        React.createElement('span', { className: 'fd-sign' }, line.kind === 'add' ? '+' : line.kind === 'del' ? '-' : ' '),
        React.createElement('span', { className: 'fd-text' }, line.text)))
      return React.createElement('div', { className: 'fd-hunk' }, ...elements)
    }

    // Renders the cumulative diff for a before/after pair; yields the stats.
    const useCumulative = (before, after) => React.useMemo(() => computeDiff(before, after), [before, after])

    const CumulativeBody = ({ before, after }) => {
      const diff = useCumulative(before, after)
      if (diff.rows.length === 0) {
        return React.createElement('div', { className: 'fd-netzero' }, 'No net change in this window.')
      }
      return React.createElement(RowLines, { rows: diff.rows })
    }

    const ChangeEntry = ({ entry, index, ordinal, total }) => {
      const [open, setOpen] = React.useState(true)
      const header = React.createElement('button', { type: 'button', className: 'fd-change', onClick: () => setOpen(!open) },
        React.createElement('span', { className: 'fd-change-path' }, entry.path),
        ordinal === undefined ? null : React.createElement('span', { className: 'fd-change-index' }, `${ordinal}/${total}`))
      if (!open) return header
      return React.createElement(React.Fragment, null, header, React.createElement(Hunk, { hunk: entry }))
    }

    // "path — total diff of one file within one user-message window."
    const FileTotalRow = ({ agg }) => {
      const [open, setOpen] = React.useState(true)
      const diff = useCumulative(agg.before, agg.after)
      const meta = `+${diff.adds} \u2212${diff.dels} \u00b7 ${agg.hunks} change${agg.hunks === 1 ? '' : 's'} in this message`
      const header = React.createElement('button', { type: 'button', className: 'fd-total', onClick: () => setOpen(!open) },
        React.createElement('span', { className: 'fd-total-path' }, agg.path),
        React.createElement('span', { className: 'fd-total-meta' }, meta))
      if (!open) return React.createElement('div', { className: 'fd-total-body' }, header)
      return React.createElement('div', { className: 'fd-total-body' },
        header,
        React.createElement(CumulativeBody, { before: agg.before, after: agg.after }))
    }

    // Memoized: the rail's active mark changes as the reader scrolls, and without
    // this guard each of those commits would reconcile every row of every diff in
    // the session. Its props are the memoized model section, aggregation list, and
    // Turn scalars, so they are stable unless the changes themselves move.
    const Section = React.memo(function Section({ section, startIndex, aggregates, turn, answer, answerIsOwn, answerLoadSeq, active, onResize, onLoadTurn }) {
      const [open, setOpen] = React.useState(true)
      const [showDetails, setShowDetails] = React.useState(false)
      const [showAnswer, setShowAnswer] = React.useState(false)
      const [loadingAnswer, setLoadingAnswer] = React.useState(false)
      const headerRef = React.useRef(null)
      // The floating card belongs to the message you are reading. Once another
      // message's header pins over this one, an open card would hover over the wrong
      // diffs, so it only shows while its own section is the active one. An unknown
      // active Turn (nothing measured yet) must not lock the card shut.
      const answerOpen = showAnswer && answer !== '' && (active !== false || turn === null)
      React.useEffect(() => {
        if (!answerOpen) return undefined
        const onKeyDown = (event) => {
          if (event.key === 'Escape') setShowAnswer(false)
        }
        const onPointerDown = (event) => {
          const target = event.target
          const inHeader = headerRef.current !== null
            && target !== null
            && typeof target.closest === 'function'
            && headerRef.current.contains(target)
          if (!inHeader) setShowAnswer(false)
        }
        document.addEventListener('keydown', onKeyDown)
        document.addEventListener('pointerdown', onPointerDown, true)
        return () => {
          document.removeEventListener('keydown', onKeyDown)
          document.removeEventListener('pointerdown', onPointerDown, true)
        }
      }, [answerOpen])
      // Collapsing the section and opening the card both change the header's height,
      // and the header is the sticky offset its own file rows pin beneath.
      React.useEffect(() => {
        if (typeof onResize === 'function') onResize()
      }, [open, answerOpen, showDetails, onResize])
      const loadAnswer = () => {
        if (typeof onLoadTurn !== 'function' || !Number.isSafeInteger(answerLoadSeq)) return
        setLoadingAnswer(true)
        Promise.resolve(onLoadTurn(answerLoadSeq)).catch(() => {}).then(() => {
          setLoadingAnswer(false)
        })
      }
      const count = section.changes.length
      const uniquePaths = []
      const seen = new Set()
      for (const change of section.changes) {
        if (!seen.has(change.path)) {
          seen.add(change.path)
          uniquePaths.push(change.path)
        }
      }
      // One uniform total row per file (1 change or many). Files with ≥ 2
      // changes in this message additionally keep their per-change hunks
      // hidden behind a single message-wide toggle. Files whose history could
      // not be reconstructed (no total row) fall back to visible per-change
      // entries.
      const covered = new Set()
      const multiPaths = new Map()
      let hiddenCount = 0
      for (const agg of aggregates) {
        covered.add(agg.path)
        if (agg.hunks >= 2) {
          multiPaths.set(agg.path, agg.hunks)
          hiddenCount += agg.hunks
        }
      }
      const entries = []
      for (const agg of aggregates) {
        entries.push(React.createElement(FileTotalRow, { key: `total-${agg.path}`, agg }))
      }
      if (hiddenCount > 0) {
        entries.push(React.createElement('div', { key: 'detail', className: 'fd-inset' },
          React.createElement('button', { type: 'button', className: 'fd-older', onClick: () => setShowDetails(!showDetails) },
            showDetails ? `Hide ${hiddenCount} individual change${hiddenCount === 1 ? '' : 's'}` : `Show ${hiddenCount} individual change${hiddenCount === 1 ? '' : 's'}`)))
      }
      if (showDetails) {
        const ordinals = new Map()
        for (let i = 0; i < section.changes.length; i += 1) {
          const change = section.changes[i]
          if (!multiPaths.has(change.path)) continue
          const ordinal = (ordinals.get(change.path) || 0) + 1
          ordinals.set(change.path, ordinal)
          entries.push(React.createElement(ChangeEntry, { key: `c-${startIndex + i}`, entry: change, index: startIndex + i, ordinal, total: multiPaths.get(change.path) }))
        }
      }
      for (let i = 0; i < section.changes.length; i += 1) {
        const change = section.changes[i]
        if (covered.has(change.path)) continue
        entries.push(React.createElement(ChangeEntry, { key: `f-${startIndex + i}`, entry: change, index: startIndex + i }))
      }
      // The loaded history window can start mid-turn, so the user message that
      // opened the oldest section may not be in the log yet. Give that section
      // the same sticky header chrome as every other one — with an honest
      // placeholder label — instead of leaving its file rows ungrouped and
      // visually different from the sections below it. A user message whose
      // text blocks are all empty (e.g. an image-only prompt) gets a matching
      // fallback so the header is never blank.
      const earlier = section.user === null
      const userLabel = earlier ? 'Earlier messages not loaded' : (section.user === '' ? '(message has no text)' : section.user)
      const headerClass = `fd-section-user ${open ? 'fd-section-open' : 'fd-section-closed'}${earlier ? ' fd-section-earlier' : ''}${answerOpen ? ' fd-section-answer-open' : ''}`
      const metaLabel = answerIsOwn === true
        ? (turn === null ? 'Answer' : `Answer \u00b7 message ${turn}`)
        : (turn === null ? 'Answer (preview)' : `Answer (preview) \u00b7 message ${turn}`)
      const header = React.createElement('div', {
        className: headerClass,
        ref: headerRef,
        'data-fd-turn': turn === null || turn === undefined ? undefined : String(turn),
      },
        React.createElement('div', { className: 'fd-section-user-row', onClick: () => setOpen(!open) },
          React.createElement('button', { type: 'button', className: 'fd-section-user-toggle', 'aria-expanded': open },
            React.createElement('span', { className: 'fd-section-user-chevron' }, '\u25b8'),
            React.createElement('span', { className: 'fd-section-user-text' }, userLabel)),
          React.createElement('span', { className: 'fd-section-user-count' }, `${count} change${count === 1 ? '' : 's'}`),
          answer === '' ? null : React.createElement('button', {
            type: 'button',
            className: 'fd-section-user-answer-toggle',
            'aria-expanded': answerOpen,
            onClick: (event) => {
              event.stopPropagation()
              setShowAnswer(!showAnswer)
            },
          }, 'Answer')),
        answerOpen
          ? React.createElement('div', { className: 'fd-section-answer', role: 'dialog', 'aria-label': 'Assistant answer for this message' },
            answerIsOwn === true && !Number.isSafeInteger(answerLoadSeq)
              ? null
              : React.createElement('div', { className: 'fd-section-answer-meta' },
                React.createElement('span', null, metaLabel),
                Number.isSafeInteger(answerLoadSeq)
                  ? React.createElement('button', {
                    type: 'button',
                    className: 'fd-section-answer-load',
                    disabled: loadingAnswer,
                    onClick: loadAnswer,
                  }, loadingAnswer ? 'Loading\u2026' : 'Load this message')
                  : null),
            React.createElement(AnswerText, { text: answer, className: 'fd-section-answer-text' }))
          : null,
        open ? null : React.createElement('span', { className: 'fd-section-user-files' }, uniquePaths.join(' \u00b7 ')))
      if (!open) return React.createElement('div', { className: 'fd-section' }, header)
      return React.createElement('div', { className: 'fd-section' }, header, ...entries)
    })

    // ------------------------------------------------------------------ //
    // File mode: one cumulative diff per file                             //
    // ------------------------------------------------------------------ //
    const FileGroup = ({ path, group }) => {
      const [open, setOpen] = React.useState(true)
      const [showDetail, setShowDetail] = React.useState(false)
      const plan = group.plan
      const totalBefore = plan.ok ? plan.states[0] : ''
      const totalAfter = plan.ok ? plan.states[plan.states.length - 1] : ''
      const diff = useCumulative(totalBefore, totalAfter)
      const suffixParts = []
      if (plan.created) suffixParts.push('new file')
      if (plan.ok) suffixParts.push(`+${diff.adds} \u2212${diff.dels}`)
      const suffix = suffixParts.length === 0 ? '' : ` \u00b7 ${suffixParts.join(' \u00b7 ')}`
      const header = React.createElement('button', { type: 'button', className: 'fd-change', onClick: () => setOpen(!open) },
        React.createElement('span', { className: 'fd-change-path' }, path),
        React.createElement('span', { className: 'fd-change-index' }, `${group.changeCount} change${group.changeCount === 1 ? '' : 's'}${suffix}`))
      if (!open) return React.createElement('div', { className: 'fd-section' }, header)
      const body = []
      if (plan.ok) {
        body.push(React.createElement(CumulativeBody, { key: 'total', before: plan.states[0], after: plan.states[plan.states.length - 1] }))
        if (plan.diverged) {
          body.push(React.createElement('div', { key: 'diverged', className: 'fd-reason' },
            'Note: this file was also modified after this session; the cumulative diff below covers the session\u2019s changes only.'))
        }
        body.push(React.createElement('div', { key: 'detail', className: 'fd-inset' },
          React.createElement('button', { type: 'button', className: 'fd-older', onClick: () => setShowDetail(!showDetail) },
            showDetail ? 'Hide individual changes' : `Show ${group.changeCount} individual change${group.changeCount === 1 ? '' : 's'}`),
          showDetail ? group.hunks.map((hunk, index) => React.createElement(Hunk, { key: index, hunk })) : null))
      } else {
        if (plan.reason !== '') {
          body.push(React.createElement('div', { key: 'reason', className: 'fd-reason' }, plan.reason))
        }
        body.push(React.createElement('div', { key: 'hunks', className: 'fd-inset' }, ...group.hunks.map((hunk, index) => React.createElement(Hunk, { key: index, hunk }))))
      }
      return React.createElement('div', { className: 'fd-section' }, header, ...body)
    }

    // ------------------------------------------------------------------ //
    // Turn navigator rail                                                 //
    // ------------------------------------------------------------------ //
    // Port of the Chat tab's rail (its component is not exported to plugins).
    // A mark is one Turn: loaded Turns scroll this view, Turns outside the loaded
    // window are paged in first. The ladder merges the same two sources Chat merges
    // — the loaded turn navigation index and the `turnOutline` projection — so it
    // matches the Chat rail turn for turn.
    const RAIL_STEP_PX = 10
    const RAIL_INSET_PX = 6
    const RAIL_AT_REST = { top: 0, canScrollUp: false, canScrollDown: false }

    const railItemPosition = (index) => ({ '--fd-rail-natural-position': `${String(index * RAIL_STEP_PX)}px` })
    const railFrameStyle = (count, scrollTop) => ({
      '--fd-rail-natural-height': `${String((count - 1) * RAIL_STEP_PX + 2 * RAIL_INSET_PX)}px`,
      '--fd-rail-inset': `${String(RAIL_INSET_PX)}px`,
      '--fd-rail-scroll-top': `${String(scrollTop)}px`,
    })

    // Pointer y -> mark index. Fixed pitch, so this is arithmetic, not hit-testing.
    const railItemAtPointer = (items, frame, scrollTop, clientY) => {
      const offset = clientY - frame.getBoundingClientRect().top + scrollTop - RAIL_INSET_PX
      return items[Math.max(0, Math.min(items.length - 1, Math.round(offset / RAIL_STEP_PX)))]
    }

    const railScrollState = (scroller) => {
      const top = scroller.scrollTop
      return {
        top,
        canScrollUp: top > 1,
        canScrollDown: top < scroller.scrollHeight - scroller.clientHeight - 1,
      }
    }

    const sameRailScrollState = (left, right) => left.top === right.top
      && left.canScrollUp === right.canScrollUp
      && left.canScrollDown === right.canScrollDown

    // Memoized for the same reason the shipped rail is: the enclosing view
    // re-renders whenever the active Turn changes, and a long session holds
    // hundreds of marks.
    const Rail = React.memo(function Rail({ items, activeTurn, busyTurn, onNavigate }) {
      const [previewTurn, setPreviewTurn] = React.useState(null)
      const [scrollState, setScrollState] = React.useState(RAIL_AT_REST)
      const scrollerRef = React.useRef(null)
      // While the pointer works the rail, the active mark must not move it under the hand.
      const pointerInsideRef = React.useRef(false)
      const previewId = React.useId()
      const syncScrollState = () => {
        const scroller = scrollerRef.current
        if (scroller === null) return
        const next = railScrollState(scroller)
        setScrollState((current) => (sameRailScrollState(current, next) ? current : next))
      }
      React.useEffect(() => {
        const scroller = scrollerRef.current
        if (scroller === null || typeof ResizeObserver === 'undefined') return undefined
        const observer = new ResizeObserver(syncScrollState)
        observer.observe(scroller)
        return () => { observer.disconnect() }
      }, [])
      React.useEffect(syncScrollState, [items.length])
      // Keep the active mark inside the rail's own scroll frame.
      React.useEffect(() => {
        const scroller = scrollerRef.current
        const index = items.findIndex((item) => item.turn === activeTurn)
        if (scroller === null || index < 0 || pointerInsideRef.current) return
        const markTop = index * RAIL_STEP_PX + RAIL_INSET_PX
        const viewTop = scroller.scrollTop
        const viewHeight = scroller.clientHeight
        if (viewHeight <= 0 || (markTop >= viewTop + 24 && markTop <= viewTop + viewHeight - 24)) return
        const target = Math.max(0, markTop - viewHeight / 2)
        const reduced = typeof matchMedia === 'function' && matchMedia('(prefers-reduced-motion: reduce)').matches
        if (typeof scroller.scrollTo === 'function') scroller.scrollTo({ top: target, behavior: reduced ? 'auto' : 'smooth' })
        else scroller.scrollTop = target
        syncScrollState()
      }, [activeTurn, items])
      if (items.length < 2) return null
      const previewIndex = items.findIndex((item) => item.turn === previewTurn)
      const preview = previewIndex < 0 ? undefined : items[previewIndex]
      const previewPosition = previewIndex < 0 ? undefined : railItemPosition(previewIndex)
      const scrollTopNow = () => (scrollerRef.current === null ? 0 : scrollerRef.current.scrollTop)
      // The note card is a descendant of the frame and takes pointer events, so the
      // pointer can travel onto it and scroll a long answer. Events originating
      // inside the card must not re-hit-test the rail (that would swap the note out
      // from under the pointer) nor navigate.
      const fromPreview = (event) => {
        const target = event.target
        return target !== null
          && typeof target === 'object'
          && typeof target.closest === 'function'
          && target.closest('.fd-rail-preview') !== null
      }
      const previewAtPointer = (event) => {
        if (fromPreview(event)) return
        const item = railItemAtPointer(items, event.currentTarget, scrollTopNow(), event.clientY)
        setPreviewTurn(item === undefined ? null : item.turn)
      }
      const navigateAtPointer = (event) => {
        if (fromPreview(event)) return
        const item = railItemAtPointer(items, event.currentTarget, scrollTopNow(), event.clientY)
        if (item !== undefined) onNavigate(item)
      }
      const fadeClasses = ['fd-rail-scroller']
      if (scrollState.canScrollUp) fadeClasses.push('fd-rail-fade-top')
      if (scrollState.canScrollDown) fadeClasses.push('fd-rail-fade-bottom')
      return React.createElement('div', { className: 'fd-rail-slot' },
        React.createElement('nav', {
          className: 'fd-rail-frame',
          style: railFrameStyle(items.length, scrollState.top),
          'aria-label': 'Turn navigation',
          onClick: navigateAtPointer,
          onPointerMove: previewAtPointer,
          onPointerEnter: () => { pointerInsideRef.current = true },
          onPointerLeave: () => {
            pointerInsideRef.current = false
            setPreviewTurn(null)
          },
        },
        React.createElement('div', {
          ref: scrollerRef,
          className: fadeClasses.join(' '),
          onScroll: syncScrollState,
        }, React.createElement('div', { className: 'fd-rail-marks' },
          items.map((item, index) => {
            const active = item.turn === activeTurn
            const showingPreview = item.turn === previewTurn
            const classes = ['fd-rail-mark']
            if (item.anchor === 'unloaded') classes.push('fd-rail-mark-unloaded')
            else if (item.hasChanges !== true && !active) classes.push('fd-rail-mark-nodiff')
            if (active) classes.push('fd-rail-mark-active')
            else if (showingPreview) classes.push('fd-rail-mark-preview')
            if (item.turn === busyTurn) classes.push('fd-rail-mark-busy')
            return React.createElement('div', { className: 'fd-rail-mark-position', style: railItemPosition(index), key: item.turn },
              React.createElement('button', {
                type: 'button',
                className: classes.join(' '),
                'aria-label': item.anchor === 'loaded' ? `Jump to message ${item.turn}` : `Load and jump to message ${item.turn}`,
                'aria-current': active ? 'true' : undefined,
                'aria-busy': item.turn === busyTurn ? 'true' : undefined,
                'aria-describedby': showingPreview ? previewId : undefined,
                onClick: (event) => {
                  event.stopPropagation()
                  onNavigate(item)
                },
                onFocus: () => setPreviewTurn(item.turn),
                onBlur: () => setPreviewTurn(null),
              }))
          }))),
        preview !== undefined && previewPosition !== undefined
          ? React.createElement('div', { id: previewId, role: 'tooltip', className: 'fd-rail-preview', style: previewPosition },
            React.createElement('div', { className: 'fd-rail-preview-prompt' }, preview.prompt === '' ? `Message ${preview.turn}` : preview.prompt),
            preview.answer !== ''
              ? React.createElement(AnswerText, { text: preview.answer, className: 'fd-rail-preview-answer' })
              : (preview.response !== ''
                ? React.createElement(AnswerText, { text: preview.response, className: 'fd-rail-preview-answer' })
                : React.createElement('div', { className: 'fd-rail-preview-answer fd-rail-preview-answer-muted' }, 'No answer recorded for this message.')),
            preview.detail === '' ? null : React.createElement('div', { className: 'fd-rail-preview-detail' }, preview.detail))
          : null))
    })

    // ------------------------------------------------------------------ //
    // View                                                                //
    // ------------------------------------------------------------------ //
    const FilesView = ({ useSession, useSessions, useConversation, useProjection, useChat, sessionId, loadOlder, loadThrough }) => {
      // Current harness: the assembled conversation nodes live on the Chat view
      // target's compatibility slice (`useConversation` -> views.get('chat') ->
      // legacy.nodes); the lifecycle snapshot (`useSession`) carries no nodes.
      // Older harnesses exposed the nodes directly on the session snapshot, so
      // that path is kept as a fallback.
      const chatNodes = typeof useConversation === 'function'
        ? useConversation((snap) => {
          if (snap === null || snap === undefined || typeof snap !== 'object') return undefined
          const views = snap.views
          if (views === null || views === undefined || typeof views.get !== 'function') return undefined
          const chat = views.get('chat')
          if (chat === null || chat === undefined || typeof chat !== 'object') return undefined
          const legacy = chat.legacy
          if (legacy === null || legacy === undefined || typeof legacy !== 'object') return undefined
          return Array.isArray(legacy.nodes) ? legacy.nodes : undefined
        })
        : undefined
      const legacyNodes = typeof useSession === 'function'
        ? useSession((snap) => (snap !== null && typeof snap === 'object' ? snap.nodes : undefined))
        : undefined
      const nodes = Array.isArray(chatNodes) ? chatNodes : (Array.isArray(legacyNodes) ? legacyNodes : [])
      const hasMore = typeof useSession === 'function'
        ? (useSession((snap) => (snap !== null && typeof snap === 'object' ? snap.hasMore : false)) ?? false)
        : false
      const loadingOlder = typeof useSession === 'function'
        ? (useSession((snap) => (snap !== null && typeof snap === 'object' ? snap.loadingOlder : false)) ?? false)
        : false
      const cwd = useSessions((list) => list.byId[sessionId]?.cwd)
      // Rail sources, the same two the Chat view reads: the loaded turn navigation
      // index (anchors + previews for the loaded window) and the `turnOutline`
      // projection (every started turn, with the `turn/start` seq a jump pages
      // through). Both are standard `conversation.view` props; each degrades to
      // "unavailable" rather than throwing when a harness does not supply it.
      const turnOutline = typeof useProjection === 'function' ? useProjection('turnOutline') : undefined
      const turnNavigationItems = typeof useChat === 'function'
        ? useChat((snap) => {
          if (snap === null || snap === undefined || typeof snap !== 'object') return undefined
          const navigation = snap.navigation
          if (navigation === null || navigation === undefined || typeof navigation !== 'object') return undefined
          if (typeof navigation.items !== 'function') return undefined
          return navigation.items()
        })
        : undefined
      const [activeTurn, setActiveTurn] = React.useState(null)
      const [busyTurn, setBusyTurn] = React.useState(null)
      const [settleTick, setSettleTick] = React.useState(0)
      const pendingJumpRef = React.useRef(null)
      const scrollRef = React.useRef(null)
      const scrollerRef = React.useRef(null)
      const updateSticky = () => {
        const container = scrollRef.current
        if (container === null) return
        const scroller = scrollerRef.current ?? container
        const top = scroller.getBoundingClientRect().top
        // The pinned section header is also the rail's active Turn: the last header
        // at or above the reading line owns what the reader is looking at.
        const sectionEls = container.querySelectorAll('.fd-section-user')
        let pinned = null
        for (let i = sectionEls.length - 1; i >= 0; i -= 1) {
          if (sectionEls[i].getBoundingClientRect().top <= top + 1) {
            pinned = sectionEls[i]
            break
          }
        }
        if (pinned === null && sectionEls.length > 0) pinned = sectionEls[0]
        const offset = pinned === null ? 0 : pinned.offsetHeight
        const nextTurn = pinned === null ? null : Number(pinned.getAttribute('data-fd-turn'))
        const active = Number.isSafeInteger(nextTurn) ? nextTurn : null
        setActiveTurn((current) => (current === active ? current : active))
        container.style.setProperty('--fd-sticky-offset', `${offset}px`)
        const stickyEls = container.querySelectorAll('.fd-change, .fd-total')
        let stuck = null
        const limit = top + offset + 1
        for (const el of stickyEls) {
          if (el.getBoundingClientRect().top <= limit) stuck = el
        }
        for (const el of stickyEls) {
          if (el === stuck) el.classList.add('fd-stuck')
          else el.classList.remove('fd-stuck')
        }
      }
      // Collapsing a section, and opening its answer card, both change the header's
      // height, so the pinned offset its file rows sit under must be re-measured. The
      // state lives inside
      // the memoized Section, which does not re-render this view, so the ref is kept
      // current on every render and the stable callback below lets a child ask for
      // the re-measure without making Section's props unstable.
      const updateStickyRef = React.useRef(null)
      updateStickyRef.current = updateSticky
      const notifyLayoutChange = React.useCallback(() => {
        const run = updateStickyRef.current
        if (run !== null) run()
      }, [])
      React.useEffect(() => { updateSticky() })
      React.useEffect(() => {
        const container = scrollRef.current
        if (container === null) return undefined
        let scroller = null
        let onScroll = null
        let observer = null
        let frame = 0
        let timer = 0
        // Re-walk the ancestor chain after every layout change. At first mount the
        // conversation nodes — and with them the Files content — can still be
        // arriving, so a one-shot walk locks the view to a self-scrolling container
        // whose scrollport never moves; the sticky headers then never pin.
        const detect = () => {
          let found = null
          let el = container
          while (el !== null) {
            const style = getComputedStyle(el)
            if ((style.overflowY === 'auto' || style.overflowY === 'scroll') && el.scrollHeight > el.clientHeight + 1) {
              found = el
              break
            }
            el = el.parentElement
          }
          let blocked = false
          if (found !== null && found !== container) {
            let cur = container.parentElement
            while (cur !== null && cur !== found) {
              const style = getComputedStyle(cur)
              if (style.overflowX !== 'visible' || style.overflowY !== 'visible') {
                blocked = true
                break
              }
              cur = cur.parentElement
            }
          }
          const next = blocked || found === null ? container : found
          container.style.overflow = next === container ? 'auto' : 'visible'
          if (next !== scroller) {
            if (scroller !== null && onScroll !== null) scroller.removeEventListener('scroll', onScroll)
            scroller = next
            scrollerRef.current = scroller
            onScroll = () => updateSticky()
            scroller.addEventListener('scroll', onScroll, { passive: true })
            observer.observe(scroller)
          }
          updateSticky()
        }
        observer = new ResizeObserver(() => detect())
        observer.observe(container)
        detect()
        frame = requestAnimationFrame(() => { detect(); frame = requestAnimationFrame(detect) })
        timer = setTimeout(detect, 100)
        return () => {
          if (frame !== 0) cancelAnimationFrame(frame)
          if (timer !== 0) clearTimeout(timer)
          if (scroller !== null && onScroll !== null) scroller.removeEventListener('scroll', onScroll)
          observer.disconnect()
        }
      }, [])
      const [mode, setMode] = React.useState(viewMode)
      const pickMode = (next) => { viewMode = next; setMode(next) }

      const model = React.useMemo(() => buildModel(nodes, cwd), [nodes, cwd])
      const files = model.files

      // Read current on-disk content of every changed file (host RPC).
      const pathsKey = files.map((f) => f.path).join('\u0001')
      const revKey = `${sessionId}\u0001${cwd}\u0001${nodes.length}\u0001${pathsKey}`
      const [reads, setReads] = React.useState({ key: '', contents: new Map(), hostOk: null })
      React.useEffect(() => {
        if (reads.key === revKey) return
        const contents = new Map()
        if (remoteFiles === undefined || files.length === 0 || cwd === undefined || cwd === '') {
          setReads({ key: revKey, contents, hostOk: false })
          return
        }
        let alive = true
        const paths = files.map((f) => f.path)
        Promise.all(paths.map((path) => readWorkspaceFile(remoteFiles, sessionId, path))).then((values) => {
          if (!alive) return
          for (let i = 0; i < paths.length; i += 1) {
            const value = values[i]
            if (typeof value === 'string') contents.set(paths[i], canonText(value))
          }
          setReads({ key: revKey, contents, hostOk: true })
        }).catch(() => {
          if (alive) setReads({ key: revKey, contents, hostOk: false })
        })
        return () => { alive = false }
      }, [revKey])

      const plans = React.useMemo(() => {
        const map = new Map()
        for (const file of files) {
          const disk = reads.contents.get(file.path)
          map.set(file.path, buildPlan(file, disk === undefined ? null : disk))
        }
        return map
      }, [files, reads])

      // Per-message total entries for the Timeline mode: one entry per file per
      // user-message window in which the file was changed at all.
      const aggBySection = React.useMemo(() => {
        const map = new Map()
        const add = (sec, entry) => {
          let list = map.get(sec)
          if (list === undefined) {
            list = []
            map.set(sec, list)
          }
          list.push(entry)
        }
        for (const file of files) {
          const plan = plans.get(file.path)
          if (plan === undefined || !plan.ok) continue
          const events = file.events
          let runStart = 0
          while (runStart < events.length) {
            const sec = events[runStart].sec
            let runEnd = runStart
            let hunksCount = 0
            while (runEnd < events.length && events[runEnd].sec === sec) {
              hunksCount += events[runEnd].hunks.length
              runEnd += 1
            }
            if (hunksCount >= 1) {
              add(sec, {
                path: file.path,
                hunks: hunksCount,
                before: plan.states[runStart],
                after: plan.states[runEnd],
              })
            }
            runStart = runEnd
          }
        }
        return map
      }, [files, plans])

      const changeCount = mode === 'session'
        ? model.sections.reduce((sum, section) => sum + section.changes.length, 0)
        : files.reduce((sum, file) => sum + file.events.reduce((n, ev) => n + ev.hunks.length, 0), 0)
      const fileCount = mode === 'session'
        ? new Set(model.sections.flatMap((section) => section.changes.map((change) => change.path))).size
        : files.length

      // Outline entries, structurally narrowed: projection values cross a wire
      // boundary, and a mark cannot exist without a safe turn + seq.
      const outlineTurns = React.useMemo(() => {
        if (!Array.isArray(turnOutline)) return []
        const list = []
        for (const raw of turnOutline) {
          if (raw === null || typeof raw !== 'object') continue
          const turn = raw.turn
          const seq = raw.seq
          if (!Number.isSafeInteger(turn) || turn < 0) continue
          if (!Number.isSafeInteger(seq) || seq < 0) continue
          list.push({
            turn,
            seq,
            prompt: typeof raw.prompt === 'string' ? raw.prompt : '',
            response: typeof raw.response === 'string' ? raw.response : '',
          })
        }
        list.sort((left, right) => left.turn - right.turn)
        return list
      }, [turnOutline])

      // Section -> Turn. A section opens on a user node whose seq sits after its
      // turn's `turn/start` seq, so the newest outline entry at or before it is the
      // owning Turn. Without the projection, align the loaded turns with the
      // sections that carry a real user message, in order.
      const sectionTurns = React.useMemo(() => {
        const turns = new Array(model.sections.length).fill(null)
        if (outlineTurns.length > 0) {
          for (let i = 0; i < model.sections.length; i += 1) {
            const seq = model.sections[i].seq
            if (!Number.isSafeInteger(seq)) continue
            let turn = null
            for (const entry of outlineTurns) {
              if (entry.seq > seq) break
              turn = entry.turn
            }
            turns[i] = turn
          }
          return turns
        }
        const loaded = []
        if (Array.isArray(turnNavigationItems)) {
          for (const item of turnNavigationItems) {
            if (item !== null && typeof item === 'object' && Number.isSafeInteger(item.turn)) loaded.push(item.turn)
          }
        }
        loaded.sort((left, right) => left - right)
        let cursor = 0
        for (let i = 0; i < model.sections.length; i += 1) {
          if (model.sections[i].user === null) continue
          if (cursor >= loaded.length) break
          turns[i] = loaded[cursor]
          cursor += 1
        }
        return turns
      }, [model.sections, outlineTurns, turnNavigationItems])

      // What a section knows for the rail note: its change count and the file list.
      const railDetailBySection = React.useMemo(() => {
        const list = new Array(model.sections.length).fill('')
        for (let i = 0; i < model.sections.length; i += 1) {
          const section = model.sections[i]
          if (section.changes.length === 0) continue
          const paths = []
          const seen = new Set()
          for (const change of section.changes) {
            if (seen.has(change.path)) continue
            seen.add(change.path)
            paths.push(change.path)
          }
          const shown = paths.slice(0, 3).join(', ')
          list[i] = `${section.changes.length} change${section.changes.length === 1 ? '' : 's'} \u00b7 ${shown}${paths.length > 3 ? ` +${paths.length - 3} more` : ''}`
        }
        return list
      }, [model.sections])

      // Merge the loaded navigation index with the outline into the full ladder:
      // a Turn on both sides keeps the loaded anchor and takes an outline preview
      // only where the window has none (a mid-Turn window head). `answer` is the
      // full text of the Turn's final assistant message when the loaded window has
      // it; `response` stays the host's bounded outline preview as the fallback for
      // Turns that are not loaded (or whose answer is not finalized yet).
      const railItems = React.useMemo(() => {
        const byTurn = new Map()
        for (const entry of outlineTurns) {
          byTurn.set(entry.turn, {
            turn: entry.turn,
            prompt: entry.prompt,
            response: entry.response,
            answer: '',
            detail: '',
            seq: entry.seq,
            anchor: 'unloaded',
            sectionIndex: -1,
            hasChanges: false,
          })
        }
        if (Array.isArray(turnNavigationItems)) {
          for (const item of turnNavigationItems) {
            if (item === null || typeof item !== 'object' || !Number.isSafeInteger(item.turn)) continue
            const previous = byTurn.get(item.turn)
            byTurn.set(item.turn, {
              turn: item.turn,
              prompt: typeof item.prompt === 'string' && item.prompt !== '' ? item.prompt : (previous === undefined ? '' : previous.prompt),
              response: typeof item.response === 'string' && item.response !== '' ? item.response : (previous === undefined ? '' : previous.response),
              answer: previous === undefined ? '' : previous.answer,
              detail: '',
              seq: previous === undefined ? null : previous.seq,
              anchor: 'loaded',
              sectionIndex: -1,
              hasChanges: false,
            })
          }
        }
        for (let i = 0; i < sectionTurns.length; i += 1) {
          const turn = sectionTurns[i]
          if (turn === null) continue
          const item = byTurn.get(turn)
          if (item === undefined || item.sectionIndex >= 0) continue
          item.sectionIndex = i
          item.detail = railDetailBySection[i]
          item.hasChanges = model.sections[i].changes.length > 0
          item.answer = model.sections[i].answer
        }
        return [...byTurn.values()].sort((left, right) => left.turn - right.turn)
      }, [outlineTurns, turnNavigationItems, sectionTurns, railDetailBySection, model.sections])

      // The answer shown next to a message's diffs: the loaded turn's own final
      // assistant message, falling back to the host's bounded outline preview for a
      // turn whose answer is not in the window (or is still streaming). `own` records
      // which of the two it is, and `loadSeq` is set only when the turn's events are
      // outside the window — the case a click can actually fix. Empty text hides the
      // Answer chip entirely.
      const answerBySection = React.useMemo(() => {
        const byTurn = new Map()
        for (const item of railItems) byTurn.set(item.turn, item)
        const list = new Array(model.sections.length).fill(null)
        for (let i = 0; i < model.sections.length; i += 1) {
          const own = model.sections[i].answer
          const turn = sectionTurns[i]
          const item = turn === null ? undefined : byTurn.get(turn)
          if (own !== '') {
            list[i] = { text: own, own: true, loadSeq: null }
            continue
          }
          if (item === undefined) continue
          list[i] = {
            text: item.response,
            own: false,
            loadSeq: item.anchor === 'unloaded' ? item.seq : null,
          }
        }
        return list
      }, [model.sections, sectionTurns, railItems])

      // One click pages a turn's messages in so the card can show the real answer
      // instead of the host's short preview.
      const loadTurnMessages = React.useCallback((seq) => {
        if (typeof loadThrough !== 'function' || !Number.isSafeInteger(seq)) return Promise.resolve()
        return Promise.resolve(loadThrough(seq)).catch(() => {}).then(() => {
          setSettleTick((tick) => tick + 1)
        })
      }, [loadThrough])

      // DOM anchors. The view renders only sections that carry changes, so a Turn
      // with no change has no header of its own: aim at the nearest following
      // section, else the nearest preceding one, so every mark lands somewhere.
      const sectionElementForTurn = (turn) => {
        const container = scrollRef.current
        if (container === null || !Number.isSafeInteger(turn)) return null
        const els = container.querySelectorAll('[data-fd-turn]')
        let after = null
        let before = null
        for (const el of els) {
          const value = Number(el.getAttribute('data-fd-turn'))
          if (!Number.isSafeInteger(value)) continue
          if (value === turn) return el
          if (value > turn && after === null) after = el
          if (value < turn) before = el
        }
        return after === null ? before : after
      }

      const scrollToSection = (el) => {
        const scroller = scrollerRef.current ?? scrollRef.current
        if (scroller === null || el === null) return
        const delta = el.getBoundingClientRect().top - scroller.getBoundingClientRect().top
        const reduced = typeof matchMedia === 'function' && matchMedia('(prefers-reduced-motion: reduce)').matches
        if (typeof scroller.scrollBy === 'function') scroller.scrollBy({ top: delta, behavior: reduced ? 'auto' : 'smooth' })
        else scroller.scrollTop += delta
      }

      const navigateToTurn = React.useCallback((item) => {
        const el = sectionElementForTurn(item.turn)
        if (item.anchor === 'loaded' || item.seq === null || typeof loadThrough !== 'function') {
          if (el !== null) scrollToSection(el)
          return
        }
        setBusyTurn(item.turn)
        pendingJumpRef.current = item.turn
        Promise.resolve(loadThrough(item.seq)).catch(() => {}).then(() => {
          setSettleTick((tick) => tick + 1)
        })
        // A jump that never lands must not leave a mark pulsing forever.
        window.setTimeout(() => {
          if (pendingJumpRef.current === item.turn) {
            pendingJumpRef.current = null
            setBusyTurn(null)
          }
        }, 4000)
      }, [loadThrough])

      // Land a pending jump as soon as the paged-in Turn's section exists. No
      // dependency list on purpose: the paged nodes can settle in a commit of
      // their own, after the promise that asked for them. `settleTick` is read so
      // that tick exists for exactly that re-check.
      React.useEffect(() => {
        void settleTick
        const pending = pendingJumpRef.current
        if (pending === null) return
        const el = sectionElementForTurn(pending)
        if (el === null) return
        pendingJumpRef.current = null
        setBusyTurn(null)
        scrollToSection(el)
      })

      const body = []
      if (hasMore && typeof loadOlder === 'function') body.push(React.createElement('button', { key: 'older', type: 'button', className: 'fd-older', disabled: loadingOlder, onClick: () => { loadOlder() } }, loadingOlder ? 'Loading older history\u2026' : 'Load older history'))
      body.push(React.createElement('div', { key: 'toggle', className: 'fd-toggle' },
        React.createElement('button', { type: 'button', className: mode === 'session' ? 'fd-toggle-active' : '', onClick: () => pickMode('session') }, 'Timeline'),
        React.createElement('button', { type: 'button', className: mode === 'file' ? 'fd-toggle-active' : '', onClick: () => pickMode('file') }, 'File')))
      if (changeCount === 0) {
        body.push(React.createElement('div', { key: 'empty', className: 'fd-empty' }, 'No file changes in this session.'))
      } else {
        body.push(React.createElement('div', { key: 'summary', className: 'fd-summary' }, `${changeCount} change${changeCount === 1 ? '' : 's'} across ${fileCount} file${fileCount === 1 ? '' : 's'}`))
        if (mode === 'session') {
          let number = 0
          for (let i = 0; i < model.sections.length; i += 1) {
            const section = model.sections[i]
            const aggregates = aggBySection.get(i)
            if (section.changes.length === 0 && (aggregates === undefined || aggregates.length === 0)) continue
            const turn = sectionTurns[i]
            const answerInfo = answerBySection[i]
            body.push(React.createElement(Section, {
              key: `s-${i}`,
              section,
              startIndex: number,
              aggregates: aggregates === undefined ? [] : aggregates,
              turn,
              answer: answerInfo === null ? '' : answerInfo.text,
              answerIsOwn: answerInfo !== null && answerInfo.own,
              answerLoadSeq: answerInfo === null ? null : answerInfo.loadSeq,
              active: turn !== null && activeTurn !== null ? turn === activeTurn : undefined,
              onResize: notifyLayoutChange,
              onLoadTurn: loadTurnMessages,
            }))
            number += section.changes.length
          }
        } else {
          for (const file of files) {
            const hunks = []
            for (const ev of file.events) {
              for (const h of ev.hunks) hunks.push(h)
            }
            body.push(React.createElement(FileGroup, { key: file.path, path: file.path, group: { changeCount: hunks.length, hunks, plan: plans.get(file.path) } }))
          }
        }
      }
      return React.createElement('div', { className: 'fd-view' },
        React.createElement('div', { ref: scrollRef, className: 'fd-scroll' },
          mode === 'session' && changeCount > 0
            ? React.createElement(Rail, {
              key: 'rail',
              items: railItems,
              activeTurn,
              busyTurn,
              onNavigate: navigateToTurn,
            })
            : null,
          ...body))
    }

    ctx.effect(() => {
      const style = document.createElement('style')
      style.setAttribute('data-dsh-plugin', 'timeline-diff')
      style.textContent = CSS
      document.head.appendChild(style)
      return () => { style.remove() }
    })

    slots.inject('conversation.view', () => slots.register({
      name: 'conversation.view',
      id: 'diff',
      order: 20,
      label: () => 'Diff',
      inject: (sessionId) => {
        const session = ctx.sessions.binding(sessionId)?.session
        if (session === undefined) throw new Error(`diff view: session "${sessionId}" is unavailable`)
        return {
          loadOlder: () => session.loadOlder(),
          // Turn-rail jumps page history through a specific Turn's `turn/start`
          // seq, exactly as the Chat view does.
          loadThrough: (seq) => session.loadThrough(seq),
        }
      },
    }, FilesView))
  },
}

module.exports = plugin

    return module.exports;
  },
});
