// Build `lib/client.js` — the `dsh.client` bundle — from `src/client.js`.
//
// The client module runtime only accepts a bundle that registers itself through
// `window.__ModuleLoader__.load({ id, factory })`, where `factory(require)`
// returns the module exports (here the Cordis plugin object). This wrapper
// supplies that envelope around the plain-CommonJS source; the module id is the
// package name, which is how `dsh.client.inject`/`external` reference it.
//
// Usage: node scripts/build-client.mjs   (or: npm run build)

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'))
const source = readFileSync(join(root, 'src', 'client.js'), 'utf8')

const header = [
  '// Generated by scripts/build-client.mjs from src/client.js — do not edit by hand.',
  'window.__ModuleLoader__.load({',
  `  id: ${JSON.stringify(pkg.name)},`,
  '  factory: (require) => {',
  '    var module = { exports: {} };',
  '    var exports = module.exports;',
  '',
].join('\n')

const footer = [
  '',
  '    return module.exports;',
  '  },',
  '});',
  '',
].join('\n')

const out = header + source + footer
mkdirSync(join(root, 'lib'), { recursive: true })
writeFileSync(join(root, 'lib', 'client.js'), out)
process.stdout.write(`build-client: wrote lib/client.js (${out.length} bytes)\n`)
